<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create the payments table.
     *
     * Stores one payment record per payment attempt.
     * A booking may have multiple payment attempts (e.g. first attempt failed, retry succeeded).
     * Only one payment per booking can have status = 'paid'.
     *
     * Payment lifecycle:
     *   pending  → initiated, awaiting provider confirmation
     *   paid     → verified by backend after provider confirmation
     *   failed   → provider rejected or verification failed
     *   cancelled → booking cancelled before payment completed
     *   refunded → provider confirmed refund
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();

            // --- Booking relationship ---
            $table->foreignId('booking_id')
                ->constrained('bookings')
                ->cascadeOnDelete();

            // --- Internal unique reference ---
            // Generated by our system. Used to identify this payment attempt uniquely.
            // Safe to share with the provider as a merchant order/reference ID.
            $table->string('reference', 64)->unique();

            // --- Provider information ---
            // Which payment provider is handling this (telebirr, cbe, chapa, cash)
            $table->string('provider', 50); // telebirr | cbe | chapa | cash

            // Which specific payment method within provider (wallet, card, etc.)
            $table->string('payment_method', 50); // matches bookings.payment_method

            // --- Amount ---
            // Amount calculated server-side. NEVER trusted from frontend.
            $table->decimal('amount', 12, 2);
            $table->string('currency', 10)->default('ETB');

            // --- Provider transaction reference ---
            // The transaction/reference ID returned by the payment provider.
            // Null until the provider responds.
            $table->string('provider_reference', 255)->nullable();

            // --- Payment status ---
            $table->string('status', 50)->default('pending');
            // Allowed: pending | paid | failed | cancelled | refunded

            // --- Timestamps for lifecycle events ---
            $table->timestamp('paid_at')->nullable();
            $table->timestamp('failed_at')->nullable();
            $table->timestamp('refunded_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();

            // --- Provider response metadata ---
            // Store raw provider callback/response for audit. Never expose to frontend.
            $table->json('provider_metadata')->nullable();

            // --- Refund information ---
            $table->string('refund_reference', 255)->nullable();
            $table->text('failure_reason')->nullable();

            $table->timestamps();

            // --- Indexes ---
            $table->index('booking_id');
            $table->index('status');
            $table->index('provider');
            $table->index('provider_reference');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
